# **Data Wrangling Lab**

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [1]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [2]:
#et column data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [3]:
#Get missing values per column
df.isnull().sum()

ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly    42002
JobSat                 36311
Length: 114, dtype: int64

In [4]:
#percentage of missing values:

df.isnull().mean() * 100

ResponseId              0.000000
MainBranch              0.000000
Age                     0.000000
Employment              0.000000
RemoteWork             16.246160
                         ...
JobSatPoints_11        55.002522
SurveyLength           14.143375
SurveyEase             14.057796
ConvertedCompYearly    64.186928
JobSat                 55.490013
Length: 114, dtype: float64

In [5]:
#Combined summary (clean view)
summary = pd.DataFrame({
    "Data Type": df.dtypes,
    "Non-Null Count": df.notnull().sum(),
    "Missing Values": df.isnull().sum(),
    "Missing %": df.isnull().mean() * 100
})

summary

                    Data Type  Non-Null Count  Missing Values  Missing %
ResponseId              int64           65437               0   0.000000
MainBranch             object           65437               0   0.000000
Age                    object           65437               0   0.000000
Employment             object           65437               0   0.000000
RemoteWork             object           54806           10631  16.246160
...                       ...             ...             ...        ...
JobSatPoints_11       float64           29445           35992  55.002522
SurveyLength           object           56182            9255  14.143375
SurveyEase             object           56238            9199  14.057796
ConvertedCompYearly   float64           23435           42002  64.186928
JobSat                float64           29126           36311  55.490013

[114 rows x 4 columns]

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [6]:
#Direct summary of numerical columns
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [7]:
#Explicitly select only numerical columns (recommended)
df.select_dtypes(include=['int64', 'float64']).describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [8]:
#include all numeric types safely
df.describe(include='number')

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [13]:
#View all unique country values
df['Country'].unique()

array(['United States Of America',
       'United Kingdom Of Great Britain And Northern Ireland', 'Canada',
       'Norway', 'Uzbekistan', 'Serbia', 'Poland', 'Philippines',
       'Bulgaria', 'Switzerland', 'India', 'Germany', 'Ireland', 'Italy',
       'Ukraine', 'Australia', 'Brazil', 'Japan', 'Austria',
       'Iran, Islamic Republic Of...', 'France', 'Saudi Arabia',
       'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden', 'Netherlands',
       'Croatia', 'Pakistan', 'Czech Republic',
       'Republic Of North Macedonia', 'Finland', 'Slovakia',
       'Russian Federation', 'Greece', 'Israel', 'Belgium', 'Mexico',
       'United Republic Of Tanzania', 'Hungary', 'Argentina', 'Portugal',
       'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon', 'Spain',
       'South Africa', 'Lithuania', 'Viet Nam', 'Dominican Republic',
       'Indonesia', 'Kosovo', 'Morocco', 'Taiwan', 'Georgia',
       'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria', 'Liechtenstein',
       'Denmark', 'Ecuador', 'Malaysia', 'Albania', 'Azerbaijan', 'Chile',
       'Ghana', 'Peru', 'Bolivia', 'Egypt', 'Luxembourg', 'Montenegro',
       'Cyprus', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Jordan',
       'Venezuela, Bolivarian Republic Of...', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'Republic Of Korea', 'Rwanda',
       'Bosnia And Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Republic Of Moldova', 'Isle Of Man', 'Nomadic',
       'New Zealand', 'Palestine', 'Armenia', 'United Arab Emirates',
       'Maldives', 'Ethiopia', 'Fiji', 'Guatemala', 'Uganda',
       'Turkmenistan', 'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas',
       'South Korea', 'Iceland', 'Honduras', 'Hong Kong (S.A.R.)',
       "Lao People'S Democratic Republic", 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'Democratic Republic Of The Congo',
       'Syrian Arab Republic', 'Iraq', 'Namibia', 'Senegal', 'Kyrgyzstan',
       'Zambia', 'Swaziland', "Côte D'Ivoire", 'Kuwait', 'Tajikistan',
       'Burundi', 'Trinidad And Tobago', 'Mauritania', 'Sierra Leone',
       'Panama', 'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo',
       'Oman', 'Barbados', 'Andorra',
       "Democratic People'S Republic Of Korea", 'Qatar', 'Sudan',
       'Cameroon', 'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi',
       'Burkina Faso', 'Congo, Republic Of The...', 'Botswana',
       'Guinea-Bissau', 'Mozambique', 'Central African Republic',
       'Equatorial Guinea', 'Suriname', 'Belize',
       'Libyan Arab Jamahiriya', 'Cape Verde', 'Brunei Darussalam',
       'Bhutan', 'Guinea', 'Niger', 'Antigua And Barbuda', 'Mali',
       'Samoa', 'Lesotho', 'Saint Kitts And Nevis', 'Monaco',
       'Micronesia, Federated States Of...', 'Haiti', nan, 'Nauru',
       'Liberia', 'Chad', 'Djibouti', 'Solomon Islands'], dtype=object)

In [14]:
#Count frequency of each country (to spot anomalies)
df['Country'].value_counts()

Country
United States Of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom Of Great Britain And Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Micronesia, Federated States Of...                          1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [15]:
#Check missing values
df['Country'].isnull().sum()

np.int64(6507)

In [16]:
#Extract problematic / inconsistent entries
#⚠️ 1. Check for missing or null values
df[df['Country'].isnull()]

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
43448,43449,"I am not primarily a developer, but I write co...",35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Contribute to open-source projects;Bootstrappi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43454,43455,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Professional development or self-paced learnin...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43459,43460,"I am not primarily a developer, but I write co...",25-34 years old,"Not employed, and not looking for work",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43460,43461,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Blogs;How-to videos;Interactive tutorial;Video...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43461,43462,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65430,65431,I am learning to code,18-24 years old,"Not employed, but looking for work;Employed, p...",In-person,Apples,Hobby;Professional development or self-paced l...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#⚠️ 2. Check for known invalid / irrelevant entries
df[df['Country'].isin(['Nomadic', '', 'Unknown', 'N/A'])]

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
1634,1635,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,Something else,Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
2464,2465,I am a developer by profession,Prefer not to say,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
6039,6040,"I am not primarily a developer, but I write co...",35-44 years old,"Not employed, and not looking for work",NaN,Apples,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
6886,6887,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
6985,6986,I am a developer by profession,Prefer not to say,"Employed, full-time",In-person,Apples,Contribute to open-source projects;Other (plea...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,10.0,30.0,27.0,5.0,0.0,10.0,Appropriate in length,Easy,64444.0,9.0
9265,9266,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,9.0
12538,12539,I am learning to code,35-44 years old,"Not employed, but looking for work",NaN,Apples,NaN,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
13137,13138,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,21481.0,NaN
14945,14946,I code primarily as a hobby,35-44 years old,I prefer not to say,NaN,Apples,NaN,Some college/university study without earning ...,Books / Physical media;Colleague;Other online ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
17784,17785,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Books;Stack Over...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Neither easy nor difficult,NaN,NaN
18078,18079,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Schoo...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,10.0,10.0,10.0,10.0,10.0,10.0,Too long,Neither easy nor difficult,NaN,7.0
19183,19184,"I used to be a developer by profession, but no...",55-64 years old,"Not employed, and not looking for work",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;S...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
22953,22954,I am a developer by profession,Prefer not to say,I prefer not to say,NaN,Apples,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;On the job training;Oth...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
23523,23524,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Contribute to open-source projects;Boots...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
26072,26073,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
26618,26619,I am a developer by profession,55-64 years old,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Colleague;Other online ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neither easy nor difficult,NaN,NaN
29127,29128,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Neither easy nor difficult,NaN,9.0
29518,29519,I am a developer by profession,Prefer not to say,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Contribute to open-source projects,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Stack Overflow;O...,...,15.0,5.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,7.0
30023,30024,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
30069,30070,I am a developer by profession,25-34 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
33205,33206,I am learning to code,Prefer not to say,I prefer not to say,NaN,Apples,NaN,Something else,Other (please specify):,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,NaN,NaN,NaN
34278,34279,I am a developer by profession,35-44 years old,"Employed, full-time;Student, full-time;Not emp...","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Other...,Something else,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,11.0,11.0,11.0,11.0,11.0,11.0,Appropriate in length,Neither easy nor difficult,NaN,10.0
34322,34323,I am learning to code,18-24 years old,"Not employed, but looking for work",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc);Other ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,NaN,NaN,NaN
34353,34354,I am a developer by profession,55-64 years old,"Employed, full-time;Independent contractor, fr...","Hybrid (some remote, some in-person)",Apples,Contribute to open-source projects;Professiona...,Something else,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Books;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,85925.0,NaN
34901,34902,I am a developer by profession,18-24 years old,"Employed, full-time",In-person,Apples,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;On the job training;Other online res...,Blogs;Stack Overflow;Coding sessions (live or ...,...,0.0,100.0,25.0,75.0,0.0,0.0,Too long,Neither easy nor difficult,NaN,4.0
35100,35101,I am a developer by profession,18-24 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Technical documentation;Written Tutorials;Stac...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
37899,37900,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
38708,38709,I am a developer by profession,45-54 years old,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Other (please specify):,NaN,...,90.0,40.0,90.0,100.0,50.0,70.0,NaN,Easy,161109.0,5.0
39684,39685,I am a developer by profession,18-24 years old,"Employed, full-time;Independent contractor, fr...","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,30.0,100.0,0.0,0.0,Too long,Neither easy nor difficult,NaN,0.0
41271,41272,I am learning to code,25-34 years old,"Not employed, but looking for work;Independent...",In-person,Apples,Contribute to open-source projects;Professiona...,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Blogs;Written Tutorials;Coding sessions (live ...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
41865,41866,I am learning to code,35-44 years old,I prefer not to say,NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Books;Written Tutorials;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
43070,43071,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
48742,48743,I am a developer by profession,35-44 years old,"Not employed, but looking for work;Independent...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;How-to videos;Interactive tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
51389,51390,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
51602,51603,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Video-based Onlin...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
52471,52472,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;Online Course...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
53637,53638,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
53666,53667,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
54866,54867,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Written Tutorials;Stack Overflow;How-to videos...,...,20.0,10.0,5.0,15.0,10.0,10.0,Appropriate in length,Neither easy nor difficult,NaN,6.0
56633,56634,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;AI,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
57319,57320,"I used to be a developer by profession, but no...",45-54 years old,I prefer not to say,NaN,Apples,NaN,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
59712,59713,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Secondary school (e.g. American high school, G...",Books / Physical media;Online Courses or Certi...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60305,60306,I am a developer by profession,18-24 years old,"Student, full-time;Independent contractor, fre...",Remote,Apples,School or academic work;Professional developme...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Stack Overflow;How-to ...,...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Easy,NaN,2.0

In [18]:
#Identify countries with unusual naming patterns (manual inspection filter)
#This helps catch long-form or inconsistent names:

df[df['Country'].str.contains(r'of|Republic|Democratic|S.A.R', na=False)]

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
37,38,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Contribute to open-source projects;Bootstrappi...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",On the job training;Online Courses or Certific...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
65,66,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Colleague;Other online resources (e.g., videos...",Blogs;Written Tutorials;Stack Overflow;How-to ...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
73,74,I am a developer by profession,35-44 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Books;Written Tu...,...,0.0,20.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,9.0
77,78,I am a developer by profession,18-24 years old,"Employed, full-time;Student, part-time","Hybrid (some remote, some in-person)",Apples,Hobby;School or academic work;Freelance/contra...,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,...,8.0,7.0,10.0,2.0,5.0,1.0,Too long,Easy,NaN,7.0
94,95,I am learning to code,Under 18 years old,"Student, part-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65116,65117,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Stack Over...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65124,65125,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;S...,...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,7.0
65146,65147,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Apples,Professional development or self-paced learnin...,"Secondary school (e.g. American high school, G...","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Written Tutorial...,...,35.0,0.0,20.0,10.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,8.0
65254,65255,I am learning to code,25-34 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;Stack Overflow;Social Media;...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65283,65284,I am learning to code,18-24 years old,"Employed, full-time;Student, part-time",Remote,Apples,School or academic work,"Secondary school (e.g. American high school, G...",Books / Physical media;Other online resources ...,Books;Stack Overflow;Social Media;How-to video...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#Find trimmed / whitespace issues
df[df['Country'] != df['Country'].str.strip()]

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
43448,43449,"I am not primarily a developer, but I write co...",35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Contribute to open-source projects;Bootstrappi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43454,43455,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Professional development or self-paced learnin...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43459,43460,"I am not primarily a developer, but I write co...",25-34 years old,"Not employed, and not looking for work",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43460,43461,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Blogs;How-to videos;Interactive tutorial;Video...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43461,43462,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65430,65431,I am learning to code,18-24 years old,"Not employed, but looking for work;Employed, p...",In-person,Apples,Hobby;Professional development or self-paced l...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
#Standardization preview check
sorted(df['Country'].dropna().unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua And Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia And Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Congo, Republic Of The...',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 "Côte D'Ivoire",
 "Democratic People'S Republic Of Korea",
 'Democratic Republic Of The Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong (S.A.R.)',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Republic Of...',
 'Iraq',
 'Ireland',
 'Isle Of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People'S Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libyan Arab Jamahiriya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Federated States Of...',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Nomadic',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic Of Korea',
 'Republic Of Moldova',
 'Republic Of North Macedonia',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Kitts And Nevis',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Taiwan',
 'Tajikistan',
 'Thailand',
 'Togo',
 'Trinidad And Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom Of Great Britain And Northern Ireland',
 'United Republic Of Tanzania',
 'United States Of America',
 'Uruguay',
 'Uzbekistan',
 'Venezuela, Bolivarian Republic Of...',
 'Viet Nam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [21]:
#🔹 Step 1: Create a mapping dictionary for Country
#Based on your dataset inconsistencies:

country_map = {
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "Iran, Islamic Republic of...": "Iran",
    "Venezuela, Bolivarian Republic of...": "Venezuela",
    "Republic of Korea": "South Korea",
    "Republic of Moldova": "Moldova",
    "Democratic People's Republic of Korea": "North Korea",
    "Congo, Republic of the...": "Congo",
    "Democratic Republic of the Congo": "Congo (DRC)",
    "Syrian Arab Republic": "Syria",
    "Lao People's Democratic Republic": "Laos"
}

In [22]:
#Apply mapping to standardize Country column
df['Country'] = df['Country'].replace(country_map)

In [23]:
#Handle whitespace and casing issues (important)
df['Country'] = df['Country'].str.strip()

In [24]:
df['Country'] = df['Country'].str.title()

In [25]:
#Standardizing EdLevel (Education Level)
#🔹 Step 4: Create mapping for EdLevel
#Example (based on Stack Overflow survey style data):

edlevel_map = {
    "Bachelor’s degree (B.Sc., B.A., etc.)": "Bachelor's",
    "Master’s degree (M.Sc., M.A., etc.)": "Master's",
    "Professional degree (JD, MD, etc.)": "Professional",
    "Some college/university study without earning a degree": "Some College",
    "Secondary school (e.g. American high school, German Realschule)": "High School",
    "Primary/elementary school": "Primary School",
    "Other doctoral degree (Ph.D., Ed.D., etc.)": "PhD"
}

In [26]:
#Apply EdLevel mapping
df['EdLevel'] = df['EdLevel'].replace(edlevel_map)

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [33]:
# One-hot encoding was already applied earlier in the dataset
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc',
       ...
       'Employment_Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time',
       'Employment_Student, full-time;Not employed, but looking for work;Retired',
       'Employment_Student, full-time;Not employed, but looking for work;Student, part-time',
       'Employment_Student, full-time;Retired',
       'Employment_Student, full-time;Student, part-time',
       'Employment_Student, full-time;Student, part-time;Employed, part-time',
       'Employment_Student, full-time;Student, part-time;Retired',
       'Employment_Student, part-time',
       'Employment_Student, part-time;Employed, part-time',
       'Employment_Student, part-time;Retired'],
      dtype='object', length=223)

In [35]:
pd.get_dummies(df, columns=['Employment'], drop_first=True)

KeyError: "None of [Index(['Employment'], dtype='object')] are in the [columns]"

In [31]:
#Verify encoding
df.head()

,ResponseId,MainBranch,Age,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,"Employment_Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Employment_Student, full-time;Not employed, but looking for work;Retired","Employment_Student, full-time;Not employed, but looking for work;Student, part-time","Employment_Student, full-time;Retired","Employment_Student, full-time;Student, part-time","Employment_Student, full-time;Student, part-time;Employed, part-time","Employment_Student, full-time;Student, part-time;Retired","Employment_Student, part-time","Employment_Student, part-time;Employed, part-time","Employment_Student, part-time;Retired"
0,1,I am a developer by profession,Under 18 years old,Remote,Apples,Hobby,Primary School,Books / Physical media,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,2,I am a developer by profession,35-44 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
2,3,I am a developer by profession,45-54 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
3,4,I am learning to code,18-24 years old,NaN,Apples,NaN,Some College,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,False,False,False,False,False,False,False,False,False,False
4,5,I am a developer by profession,18-24 years old,NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [36]:
#Count missing values per column
missing_counts = df.isnull().sum()
missing_counts

ResponseId                                                                  0
MainBranch                                                                  0
Age                                                                         0
RemoteWork                                                              10631
Check                                                                       0
                                                                        ...
Employment_Student, full-time;Student, part-time;Employed, part-time        0
Employment_Student, full-time;Student, part-time;Retired                    0
Employment_Student, part-time                                               0
Employment_Student, part-time;Employed, part-time                           0
Employment_Student, part-time;Retired                                       0
Length: 223, dtype: int64

In [37]:
#Sort columns by highest missing values
missing_counts.sort_values(ascending=False)

AINextMuch less integrated                                              64289
AINextLess integrated                                                   63082
AINextNo change                                                         52939
AINextMuch more integrated                                              51999
EmbeddedAdmired                                                         48704
                                                                        ...
Employment_Student, full-time;Student, part-time;Employed, part-time        0
Employment_Student, full-time;Student, part-time;Retired                    0
Employment_Student, part-time                                               0
Employment_Student, part-time;Employed, part-time                           0
Employment_Student, part-time;Retired                                       0
Length: 223, dtype: int64

In [38]:
#Show only top columns with most missing values
missing_counts.sort_values(ascending=False).head(10)

AINextMuch less integrated       64289
AINextLess integrated            63082
AINextNo change                  52939
AINextMuch more integrated       51999
EmbeddedAdmired                  48704
EmbeddedWantToWorkWith           47837
EmbeddedHaveWorkedWith           43223
ConvertedCompYearly              42002
AIToolNot interested in Using    41023
AINextMore integrated            41009
dtype: int64

In [39]:
#Show missing percentage (better for analysis)
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)
missing_percent.head(10)

AINextMuch less integrated       98.245641
AINextLess integrated            96.401119
AINextNo change                  80.900714
AINextMuch more integrated       79.464217
EmbeddedAdmired                  74.428840
EmbeddedWantToWorkWith           73.103901
EmbeddedHaveWorkedWith           66.052845
ConvertedCompYearly              64.186928
AIToolNot interested in Using    62.690832
AINextMore integrated            62.669438
dtype: float64

In [40]:
#Combine into a clean summary table (best for assignment)
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": df.isnull().mean() * 100
}).sort_values(by="Missing Values", ascending=False)

missing_summary.head(10)

                               Missing Values  Missing Percentage
AINextMuch less integrated              64289           98.245641
AINextLess integrated                   63082           96.401119
AINextNo change                         52939           80.900714
AINextMuch more integrated              51999           79.464217
EmbeddedAdmired                         48704           74.428840
EmbeddedWantToWorkWith                  47837           73.103901
EmbeddedHaveWorkedWith                  43223           66.052845
ConvertedCompYearly                     42002           64.186928
AIToolNot interested in Using           41023           62.690832
AINextMore integrated                   41009           62.669438

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [41]:
#Check missing values in the column
df['ConvertedCompYearly'].isnull().sum()

np.int64(42002)

In [42]:
#Impute using MEAN (common approach)
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].mean())

In [43]:
#Impute using MEDIAN (more robust to outliers ⭐ recommended)
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].median())

In [44]:
#Verify missing values are handled
df['ConvertedCompYearly'].isnull().sum()

np.int64(0)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [45]:
#Check missing values
df['RemoteWork'].isnull().sum()

np.int64(10631)

In [46]:
#Find the most frequent value (mode)
df['RemoteWork'].mode()[0]

'Hybrid (some remote, some in-person)'

In [47]:
#Fill missing values with mode
df['RemoteWork'] = df['RemoteWork'].fillna(df['RemoteWork'].mode()[0])

In [48]:
#Verify missing values are handled
df['RemoteWork'].isnull().sum()

np.int64(0)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [50]:
#Import scaler
from sklearn.preprocessing import MinMaxScaler

In [51]:
#Create scaler object
scaler = MinMaxScaler()

In [52]:
#Apply scaling to ConvertedCompYearly
df['ConvertedCompYearly_MinMax'] = scaler.fit_transform(df[['ConvertedCompYearly']])

In [53]:
#Verify result
df[['ConvertedCompYearly', 'ConvertedCompYearly_MinMax']].head()

   ConvertedCompYearly  ConvertedCompYearly_MinMax
0         86155.287263                      0.0053
1         86155.287263                      0.0053
2         86155.287263                      0.0053
3         86155.287263                      0.0053
4         86155.287263                      0.0053

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [54]:
#Import numpy
import numpy as np

In [55]:
#Apply log transformation
#⚠️ Important: If there are zero or missing values, use log1p (safer)

df['ConvertedCompYearly_Log'] = np.log1p(df['ConvertedCompYearly'])

In [56]:
#Verify transformation
df[['ConvertedCompYearly', 'ConvertedCompYearly_Log']].head()

   ConvertedCompYearly  ConvertedCompYearly_Log
0         86155.287263                11.363918
1         86155.287263                11.363918
2         86155.287263                11.363918
3         86155.287263                11.363918
4         86155.287263                11.363918

In [57]:
#Check skewness reduction
df['ConvertedCompYearly'].skew()
df['ConvertedCompYearly_Log'].skew()

np.float64(-4.394071138043888)

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [58]:
#Check data type (important)
df['YearsCodePro'].unique()

array([nan, '17', '27', '7', '11', '25', '12', '10', '3',
       'Less than 1 year', '18', '37', '15', '20', '6', '2', '16', '8',
       '14', '4', '45', '1', '24', '29', '5', '30', '26', '9', '33', '13',
       '35', '23', '22', '31', '19', '21', '28', '34', '32', '40', '50',
       '39', '44', '42', '41', '36', '38', 'More than 50 years', '43',
       '47', '48', '46', '49'], dtype=object)

In [59]:
#Clean the column (convert to numeric safely)
df['YearsCodePro'] = df['YearsCodePro'].replace({
    'Less than 1 year': 0,
    'More than 50 years': 50
})

In [60]:
#Convert to numeric:

df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')

In [61]:
#Create ExperienceLevel column
def experience_level(years):
    if years < 2:
        return "Beginner"
    elif years < 5:
        return "Intermediate"
    elif years < 10:
        return "Advanced"
    else:
        return "Expert"

df['ExperienceLevel'] = df['YearsCodePro'].apply(experience_level)

In [62]:
#Verify result
df[['YearsCodePro', 'ExperienceLevel']].head()

   YearsCodePro ExperienceLevel
0           NaN          Expert
1          17.0          Expert
2          27.0          Expert
3           NaN          Expert
4           NaN          Expert

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.